ARRANGE_COMPONENTS_ON_COMMON_BASE_TOOL = "arrange_components_on_common_base"
FINALIZE_COMMON_BASE_ASSEMBLY_TOOL = "finalize_common_base_assembly"
INITIALIZE_COMMON_BASE_ASSEMBLY_TOOL = "initialize_common_base_assembly"
MOVE_COMPONENTS_ON_COMMON_BASE_TOOL = "move_components_on_common_base"
